user = User.create(username: "test", password: "123456")
test1 = Test.create(name: "PreAlgebra", user_id: user.id, description: "Test your knowledge in PreAlgebra!")
test1 = Test.create(name: "Algebra", user_id: user.id, description: "Test your knowledge in Algebra!")
study1 = Study.create(name: "study1", test_id: test1.id)
multiple_choice1 = MultipleChoice.create(question: "What is 1 + 1?", choice1: "2", choice2: "3", choice3: "4", choice4: "5", test_id: "1", study_id: "1")
